version: '3.8'

services:
  db:
    image: postgres:16
    container_name: lease-tracker-db
    restart: always
    environment:
      POSTGRES_DB: lease_tracker
      POSTGRES_USER: maxtec
      POSTGRES_PASSWORD: L3@seTr@ck3r2024!
      POSTGRES_ROOT_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: lease-tracker-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data: 