version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: lease-tracker-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lease_tracker
      MYSQL_USER: maxtec
      MYSQL_PASSWORD: L3@seTr@ck3r2024!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 