-- AlterTable
ALTER TABLE `LeaseClause` MODIFY `type` ENUM('PAYMENT', 'MAINTENANCE', 'TERMINATION', 'SECURITY_DEPOSIT', 'UTILITIES', 'INSURANCE', 'OTHER', 'LEGAL', 'USE', 'PENALTY', 'RESTRICTIONS') NOT NULL;
