-- AlterTable
ALTER TABLE `LeaseRule` MODIFY `category` ENUM('PETS', 'SMOKING', 'NOISE', 'GUESTS', 'PARKING', 'MAINTENANCE', 'ALTERATIONS', 'OTHER', 'BUSINESS_HOURS', 'SIGNAGE', 'COMMON_AREAS', 'WASTE_MANAGEMENT', 'SECURITY', 'DELIVERIES', 'PEST_CONTROL', 'STAFF_ACCESS') NOT NULL;
